### ISSUE TITLE
Only one console avaliable even with multiple viewer

### ISSUE THREAD

**Issue by Czaki** [napari/napari-console#16]
When open more than one napari viewer in one process only one has an available console. Also `viewer` variable points to the viewer with the last opened console.  

![Zrzut ekranu z 2021-08-30 14-10-01](https://user-images.githubusercontent.com/3826210/131336874-90997dc4-d420-4bfd-aa1a-a700338f7062.png)

```
import napari
from skimage import data
from qtpy.QtWidgets import QApplication

app = QApplication([])

viewer1 = napari.view_image(data.astronaut(), rgb=True)
viewer2 = napari.view_image(data.astronaut(), rgb=True)

app.exec_()
```
I think that this line may produce this problem: 

https://github.com/napari/napari-console/blob/fd3a291331e052e591042850b56fd1db5815f784/napari_console/qt_console.py#L106

**Comment by sofroniewn** [comment]
Yeah this is a known issue, not sure how to fix though! Maybe @Carreau has an idea

**Comment by Carreau** [comment]
I've seen it, I think there is even another issue for that.
Issue IIRC is that the QtConsole makes use of singletons, and is really not made to be displayed twice or more.
I'm not sure the time/effort ratio is going to make this a high priority issue.

**Comment by sofroniewn** [comment]
> I've seen it, I think there is even another issue for that.

Yeah it's on main repo, here's at least one https://github.com/napari/napari/issues/1530

> Issue IIRC is that the QtConsole makes use of singletons, and is really not made to be displayed twice or more.
I'm not sure the time/effort ratio is going to make this a high priority issue.

Agreed - once we figure out the multiviewer / plugin relationship more broadly we can revisit this - maybe we also enforce a singleton but we can deal with that when we get to it

**Comment by Czaki** [comment]
So the approach of adding variables to the console should be changed to not lost reference to the first viewer.

**Comment by sofroniewn** [comment]
> So the approach of adding variables to the console should be changed to not lost reference to the first viewer.

Yeah we should probably at least address #1530

**Comment by psobolewskiPhD** [comment]
I think we can consider this closed by https://github.com/napari/napari-console/pull/39
