### ISSUE TITLE
Add tests/ configure github actions

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari-console#3]
Github actions should be configured and tests should be added

**Comment by sofroniewn** [comment]
@tlambert03 tests are failing right now because this needs `PySide2` / `PyQt5` - curious how you think we should do that? Add as optional dependencies? Do the `[all]` strategy for pip? Just add them each to our tests like we do in napari? That's what I'm leaning towards trying tomorrow. Any ideas welcome though!!

**Comment by tlambert03** [comment]
see my https://github.com/napari/napari-console/pull/7#issuecomment-762875608
