### ISSUE TITLE
Fontsize option for the console

### ISSUE THREAD

**Issue by jules-vanaret** [napari/napari-console#32]
Hi! First, I don't know if this issue (actually more of a feature request) belongs to this repo or the main Napari repo, so please redirect me if this is not the right place.

After a fresh install of Napari with the latest version, I found that the default font size of the text in the console is much smaller. I have rather bad eyesight, so that impacts me quite a bit... 😅 

Is there any way to change the font size ? The font size parameter in the "Preferences" panel only affects Viewer fonts, not the console.
If no way currently exists, is it possible to add this feature ?

**Comment by Czaki** [comment]
Currently, only bad hack:

```
font = viewer.window._qt_viewer.console._control.font()
font.setPointSize(20)
viewer.window._qt_viewer.console._control.setFont(font)
```

Yes, it is possible to add such feature. It will require fix qss in napari `napari/_qt/qt_resures/styles/_02_custom.qss` with add `  font: {{ font_size }};`  to `QtConsole > QTextEdit` entry and then fix console to use font size when applying style sheet.

**Comment by Czaki** [comment]
There is two things. 
Adding depending on theme for this it is a single line in qss. 
The bigger play is to also depends on settings state, as we allow to overwritte theme font size for application without mutation theme object itself.

**Comment by brisvag** [comment]
Yes, same discussion as https://github.com/napari/napari/pull/6689#issuecomment-1991935370 basically.

**Comment by Czaki** [comment]
Similar. Font resizing is already implemented.

**Comment by dalthviz** [comment]
Hi there, just in case, I think that a workaround for the moment is to use the console Zoom In (`Ctrl++` console shortcut). Also, to do Zoom Out I think the shortcut is `Ctrl + -` and to reset the Zoom you can use `Ctrl + 0`. So, using those shortcuts, you should be able to experience something like:

![console_zoom](https://github.com/napari/napari-console/assets/16781833/ed761fd5-b74e-4350-bd67-11f7c621b900)

**Comment by jules-vanaret** [comment]
> Hi there, just in case, I think that a workaround for the moment is to use the console Zoom In (`Ctrl++` console shortcut). Also, to do Zoom Out I think the shortcut is `Ctrl + -` and to reset the Zoom you can use `Ctrl + 0`. So, using those shortcuts, you should be able to experience something like:

Nice! Before writing the issue I thought this didn't work because I was trying ctrl ++, turns out it is ctrl shift + on my computer. Thank you very much.

**Comment by dalthviz** [comment]
Hi there, gave this a check and I think the behavior being experienced could be caused due to a shortcut collision? QtConsole has some actions to handle zoom via `Ctrl + +` (zoom in), `Ctrl + -` (zoom out) and `Ctrl + 0` (reset zoom). Checking with napari 0.6.3 and napari-console 0.1.3 on Windows I'm only able to use the `Ctrl + +` shortcut from the console. The others show a `WARNING: QAction::event: Ambiguous shortcut overload`:

    12:26:38 : WARNING : MainThread : QAction::event: Ambiguous shortcut overload: Ctrl+-
    WARNING: QAction::event: Ambiguous shortcut overload: Ctrl+-
    12:26:38 : WARNING : MainThread : QAction::event: Ambiguous shortcut overload: Ctrl+-
    WARNING: QAction::event: Ambiguous shortcut overload: Ctrl+0

I think the warning is shown since the `View > Zoom out` and `View > Fit to view` use those shorcuts too? 🤔
